<b>Hyperparameter:  </b> Modelin karakteristiğini belirlemek için kullandığımız parametreler. Bu parametrelerle modelin özelliklerini belirliyoruz. lr,C,lambda,optimizer,loss<br>
<b>GridSearch : </b> Bu hyperparametreleri tune etmek için kullandığımız bir yöntem


In [10]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [11]:
columns = ["Sample code number","Clump Thickness","Uniformity of Cell Size","Uniformity of Cell Shape","Marginal Adhesion","Single Epithelial Cell Size","Bare Nuclei","Bland Chromatin","Normal Nucleoli","Mitoses","Class"]
data = pd.read_csv("D:/MachineLearningCourse/Datasets/cancer.csv",names=columns,header=None)
data.head()


Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [12]:
data["Class"].value_counts()

2    458
4    241
Name: Class, dtype: int64

In [13]:
data.drop(["Sample code number"],axis=1,inplace=True)
data = data[data["Bare Nuclei"]!="?"]
data["Class"] =np.where(data.Class==2,0,1)    ## eğer değer 2 ye eşitse 0 döndür dğeilse 1 
data["Class"].value_counts()

0    444
1    239
Name: Class, dtype: int64

In [14]:
X = data.iloc[:,:9]
y = data.iloc[:,9]

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

##### Dummy Classifier

In [19]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier(strategy="most_frequent").fit(X_train,y_train)
y_pred = clf.predict(X_test)

print("y actual : ",y_test.value_counts())

print("y predicted : ",pd.Series(y_pred).value_counts())

y actual :  0    103
1     68
Name: Class, dtype: int64
y predicted :  0    171
dtype: int64


In [22]:
from sklearn.metrics import f1_score,precision_score,recall_score,accuracy_score

print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

0.6023391812865497
0.0
0.0
0.0


C:\Users\bagat\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[103,   0],
       [ 68,   0]], dtype=int64)

In [23]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression().fit(X_train,y_train)
y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred)))
print('Precision Score : ' + str(precision_score(y_test,y_pred)))
print('Recall Score : ' + str(recall_score(y_test,y_pred)))
print('F1 Score : ' + str(f1_score(y_test,y_pred)))

#Logistic Regression Classifier Confusion matrix
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))

Accuracy Score : 0.9532163742690059
Precision Score : 0.9838709677419355
Recall Score : 0.8970588235294118
F1 Score : 0.9384615384615386
Confusion Matrix : 
[[102   1]
 [  7  61]]


In [ ]:
grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values,scoring = 'recall')
grid_clf_acc.fit(X_train, y_train)

In [30]:
#Grid Search
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()
grid_values = {'penalty':['l1','l2'],'C':np.logspace(-3,3,6)}
grid = GridSearchCV(clf,param_grid=grid_values,scoring="recall")
grid.fit(X_train,y_train)

#Predict values based on new parameters
y_pred_acc = grid.predict(X_test)

# New Model Evaluation metrics 
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test,y_pred_acc)))
print('Recall Score : ' + str(recall_score(y_test,y_pred_acc)))
print('F1 Score : ' + str(f1_score(y_test,y_pred_acc)))

#Logistic Regression (Grid Search) Confusion matrix
confusion_matrix(y_test,y_pred_acc)

C:\Users\bagat\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
C:\Users\bagat\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
C:\Users\bagat\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
C:\Users\bagat\Anaconda3\lib\site-packages\

Accuracy Score : 0.9415204678362573
Precision Score : 0.9833333333333333
Recall Score : 0.8676470588235294
F1 Score : 0.9218749999999999


array([[102,   1],
       [  9,  59]], dtype=int64)

array([1.00000000e-03, 7.19685673e-03, 5.17947468e-02, 3.72759372e-01,
       2.68269580e+00, 1.93069773e+01, 1.38949549e+02, 1.00000000e+03])